# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

sudo: false

cache: packages

warnings_are_errors: false

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
